export enum ApplicationStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  SCREENING = 'SCREENING',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  PAYMENT_VERIFIED = 'PAYMENT_VERIFIED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  QUERY_RAISED = 'QUERY_RAISED',
  RESPONSE_RECEIVED = 'RESPONSE_RECEIVED',
  DECISION_PENDING = 'DECISION_PENDING',
  APPROVED = 'APPROVED',
  CONDITIONALLY_APPROVED = 'CONDITIONALLY_APPROVED',
  REJECTED = 'REJECTED',
  AMENDMENT_PENDING = 'AMENDMENT_PENDING',
  MONITORING_ACTIVE = 'MONITORING_ACTIVE',
  CLOSED = 'CLOSED',
}

export enum ApplicationType {
  FULL_BOARD = 'FULL_BOARD',
  EXPEDITED = 'EXPEDITED',
  EXEMPT = 'EXEMPT',
}

export enum ReviewRecommendation {
  APPROVE = 'APPROVE',
  APPROVE_WITH_CONDITIONS = 'APPROVE_WITH_CONDITIONS',
  REJECT = 'REJECT',
  DEFER = 'DEFER',
  ABSTAIN = 'ABSTAIN',
}

export enum DecisionType {
  APPROVED = 'APPROVED',
  CONDITIONALLY_APPROVED = 'CONDITIONALLY_APPROVED',
  REJECTED = 'REJECTED',
  DEFERRED = 'DEFERRED',
}

export enum DocumentType {
  PROTOCOL = 'PROTOCOL',
  CONSENT_FORM = 'CONSENT_FORM',
  QUESTIONNAIRE = 'QUESTIONNAIRE',
  BUDGET = 'BUDGET',
  CV = 'CV',
  ETHICS_APPROVAL = 'ETHICS_APPROVAL',
  SUPPORTING_DOCUMENT = 'SUPPORTING_DOCUMENT',
  AMENDMENT_DOCUMENT = 'AMENDMENT_DOCUMENT',
  RENEWAL_DOCUMENT = 'RENEWAL_DOCUMENT',
  PROGRESS_REPORT_DOCUMENT = 'PROGRESS_REPORT_DOCUMENT',
  AE_REPORT_DOCUMENT = 'AE_REPORT_DOCUMENT',
  DEVIATION_DOCUMENT = 'DEVIATION_DOCUMENT',
  CLOSURE_DOCUMENT = 'CLOSURE_DOCUMENT',
  OTHER = 'OTHER',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
  REFUNDED = 'REFUNDED',
}

export enum MonitoringType {
  AMENDMENT = 'AMENDMENT',
  RENEWAL = 'RENEWAL',
  PROGRESS_REPORT = 'PROGRESS_REPORT',
  ADVERSE_EVENT = 'ADVERSE_EVENT',
  PROTOCOL_DEVIATION = 'PROTOCOL_DEVIATION',
  CLOSURE_REPORT = 'CLOSURE_REPORT',
}

export enum NotificationType {
  APPLICATION_SUBMITTED = 'APPLICATION_SUBMITTED',
  QUERY_RAISED = 'QUERY_RAISED',
  QUERY_RESPONSE = 'QUERY_RESPONSE',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  PAYMENT_VERIFIED = 'PAYMENT_VERIFIED',
  REVIEWER_ASSIGNED = 'REVIEWER_ASSIGNED',
  DECISION_ISSUED = 'DECISION_ISSUED',
  CERTIFICATE_AVAILABLE = 'CERTIFICATE_AVAILABLE',
  MONITORING_REMINDER = 'MONITORING_REMINDER',
  GENERAL = 'GENERAL',
}

export enum MonitoringStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum SeverityLevel {
  MILD = 'MILD',
  MODERATE = 'MODERATE',
  SEVERE = 'SEVERE',
  LIFE_THREATENING = 'LIFE_THREATENING',
  FATAL = 'FATAL',
}
